### ISSUE TITLE
Handle response headers split across packets

### ISSUE THREAD

**Issue by nietaki** [CrowdHailer/server_sent_event.ex#9]
Currently the Client assumes the headers arrive in one packet:
https://github.com/CrowdHailer/server_sent_event.ex/blob/7b3544453acaa3881a2011fc626d2f1909701b3f/lib/server_sent_event/client.ex#L215-L221

When the header is incomplete, [`Raxx.HTTP1.parse_response/2`](https://hexdocs.pm/raxx/Raxx.HTTP1.html#parse_response/2) returns `{:more, :undefined}`

This should be solvable by buffering the request and keeping on receiving until the full header arrives.

**Comment by nietaki** [comment]
Once this gets implemented it can and probably should be added to the StreamData-powered tests, so that the server's response gets split everywhere, not just in the response body

**Comment by CrowdHailer** [comment]
@nietaki check out PR #10 I think I have property tested ok
